In [2]:
# Importing tensorflow as tf
import tensorflow as tf

In [15]:
# initialization of tensors
x = tf.constant(4.0, shape=(1,1), dtype=tf.float32)
x = tf.constant([[1, 2, 3,], [4, 5, 6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [10]:
x = tf.ones((3, 3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [13]:
x = tf.zeros((2, 3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [14]:
# I for the identity matrix (eye)
x = tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [16]:
# Standard Normal Distribution
x = tf.random.normal((3, 3), mean=0, stddev=1)
print(x)

tf.Tensor(
[[ 0.10720186 -0.5340448   1.2567586 ]
 [-0.7448153  -0.50225955 -1.513257  ]
 [-1.3799201  -0.23331465  0.2186668 ]], shape=(3, 3), dtype=float32)


In [17]:
# Uniform Distribution
x = tf.random.uniform((1, 3), minval=0, maxval= 1)
print(x)

tf.Tensor([[0.960179   0.6494317  0.20578492]], shape=(1, 3), dtype=float32)


In [21]:
x = tf.range(start=1, limit=10, delta=2)
print(x)
x = tf.cast(x, dtype=tf.float64)
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)
tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


In [22]:
# Some other operations
# tf.float (16, 32, 64), tf.int (8, 16, 32, 64), tf.bool -> 0 or 1 # Casting

In [23]:
# Mathematical Operations

In [28]:
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

In [29]:
z = tf.add(x, y)

In [30]:
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [32]:
z = x + y
print(z)# EASY

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [33]:
z = tf.subtract(x, y)

In [34]:
z = x - y

In [35]:
z = tf.divide(x, y)
z = x / y

In [36]:
print(z)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [37]:
z = tf.multiply(x, y)

In [38]:
z = x * y

In [39]:
print(z)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [40]:
z = tf.tensordot(x, y, axes=1)

In [41]:
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [43]:
z = tf.reduce_sum(x * y, axis=0)
print(x)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [46]:
z = x ** 5
print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [48]:
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))
z = tf.matmul(x, y)
print(z)
z = x @ y
print(z)

tf.Tensor(
[[-0.63480234 -1.3309538  -1.6871039  -1.5541066 ]
 [ 4.682745   -1.7742633  -1.9906085   1.2688783 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[-0.63480234 -1.3309538  -1.6871039  -1.5541066 ]
 [ 4.682745   -1.7742633  -1.9906085   1.2688783 ]], shape=(2, 4), dtype=float32)


In [53]:
x = tf.constant([0,1,1,2,3,1,2,3])
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])
#print(x[::-1])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [54]:
indices = tf.constant([0, 3])
x_ind = tf.gather(x, indices)
print(x_ind)

tf.Tensor([0 2], shape=(2,), dtype=int32)


In [56]:
x = tf.constant([[1, 2], [3, 4], [5, 6]])
print(x[0,:])
print(x[0:2, :])

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [58]:
# Reshaping
x = tf.range(9)
print(x)

x = tf.reshape(x, (3, 3))
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [59]:
x = tf.transpose(x, perm=[1, 0])
print(x)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
